on:
  push:
    branches: ["main"]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  # Enable manual trigger for easy debugging
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: "Create file"
        run: |
          mkdir /tmp/workplace
          cd /tmp/workplace

          echo -e "#!/bin/sh\necho hello world" > entrypoint.sh
          ls -lh entrypoint.sh

      - name: "Test"
        id: test
        uses: dagger/dagger-for-github@v6
        with:
          version: v0.15.2
          args: test --mydir=/tmp/workplace with-exec --args "ls,-lh,entrypoint.sh" stdout
